version: '3.8'
services:
  mysql:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=moon22
      - POSTGRES_USER=Heshedocker
      - POSTGRES_PASSWORD=moon